### ISSUE TITLE
python version 

### ISSUE THREAD

**Issue by Deeptradingfx** [HarukaMa/ctrader-fix-demo#1]
hi dear, I am testing your code looks very clean! could you tell me what´s python version you use!  i got issue on line 65 of main.py on python 3.7

**Comment by HarukaMa** [comment]
The code is using a new feature in Python 3.8 called [assignment expression](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions).

If you can't install Python 3.8, you could change it to separate lines:
```py
if (subid := int(parts[1])) < 1 or int(parts[1]) > 3:
```
to
```py
subid = int(parts[1])
if subid < 1 or subid > 3:
```

There should be some more usages like this so you need to change all of them.

**Comment by Deeptradingfx** [comment]
> The code is using a new feature in Python 3.8 called [assignment expression](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions).
> 
> If you can't install Python 3.8, you could change it to separate lines:
> 
> ```python
> if (subid := int(parts[1])) < 1 or int(parts[1]) > 3:
> ```
> 
> to
> 
> ```python
> subid = int(parts[1])
> if subid < 1 or subid > 3:
> ```
> 
> There should be some more usages like this so you need to change all of them.

thank you! now is running ok ill try it with asyncore and check the performance vs threading !! great work thanks to share and help a newbie take care!!!
