### ISSUE TITLE
have you  manage to add SL E TP from your fix api

### ISSUE THREAD

**Issue by Deeptradingfx** [HarukaMa/ctrader-fix-demo#2]
I know there are no issues with your python API! it's great but I'm trying to set SL and tp on the order I found somewhere there was possible by setting a limit order! however, the account needs to be netting  or works to on hedging account

**Comment by HarukaMa** [comment]
When you add limit / stop order you will be able to specify the existing position ID and the new order will be "linked" to the existing position. You won't see that on cTrader GUI but when the pending order get executed you are actually modifying the existing position. I think I'm displaying the linked ID on the order window.

It works on hedging account.
